export const guestText = {
  title: "はしごゆ",
  locationLabel: "いる場所",
  locationPlaceholder: "住所を入力",
  currentLocation: "現在地",
  currentLocationError: "現在地を取得できません。住所を入力してください。",
  timeLabel: "入る時間",
  countLabel: "軒数",
  routeTitle: "ルート",
  listTitle: "銭湯一覧",
  open: "営業中",
  closed: "営業時間外",
  walk: "徒歩",
  transit: "電車",
  minutes: "分",
  arrival: "到着",
  hours: "営業時間",
  map: "地図",
  price: "550円",
  unavailable: "該当なし",
  sampleNotice: "銭湯名・住所・人数・金額はすべて架空のサンプルです",
} as const;
